// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "node:path";
import { defineConfig } from "prisma/config";

const apiDir = __dirname;
const rootDir = resolve(apiDir, "../..");

// Repo root .env (docker-compose DATABASE_URL); apps/api/.env may override locally
config({ path: resolve(apiDir, ".env") });
config({ path: resolve(rootDir, ".env"), override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
